# Generated by Django 4.1 on 2022-09-12 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('threat', '0002_rename_treat_threat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(max_length=100, verbose_name='Server')),
                ('dt', models.DateTimeField(auto_now=True, verbose_name='DT log record')),
                ('comment', models.CharField(max_length=100)),
                ('threat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='threat.threat', verbose_name='Threat')),
            ],
            options={
                'verbose_name': 'Log',
                'verbose_name_plural': 'Logs',
                'ordering': ['-dt', 'server_name'],
            },
        ),
    ]
