# Generated by Django 4.1 on 2022-09-12 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThreatCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(blank=True, choices=[('ATTACK', 'Attack'), ('THREAT', 'Threat'), ('FALSEALARM', 'Falsealarm'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=10, null=True, verbose_name='Category Kind')),
            ],
            options={
                'verbose_name': 'Threat Category',
                'verbose_name_plural': 'Threat Categories',
            },
        ),
        migrations.CreateModel(
            name='Treat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='DateTime occured')),
                ('location', models.CharField(max_length=100, verbose_name='Location')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='threat.threatcategory', verbose_name='Category of the Threat')),
            ],
            options={
                'verbose_name': 'Threat',
                'verbose_name_plural': 'Threats',
                'ordering': ['-dt', 'location'],
            },
        ),
    ]
