# Generated by Django 4.1 on 2022-09-12 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threat', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Treat',
            new_name='Threat',
        ),
    ]
